version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: InstabugChat_development
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
      - "9200:9200"
      - "9300:9300"
    # volumes:
    #   - elasticsearch:/usr/share/elasticsearch/data    

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
    links:
      - db
      - elasticsearch
      
volumes:
  elasticsearch: {}
  db: {}


